services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/project
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:trivia@db:5432/trivia_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trivia
      - POSTGRES_DB=trivia_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: