name: Trivia CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Run tests
        run: |
          docker-compose exec -T web pytest tests/test_db_models_test.py tests/test_api.py tests/test_models_sqlite.py --cov=app --cov-report=xml
      
      - name: Copy coverage report from container
        run: |
          docker cp $(docker-compose ps -q web):/project/coverage.xml ./coverage.xml
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Stop containers
        if: always()
        run: docker-compose down